In [12]:
import numpy as np

In [13]:
x = np.arange(300,500,10)
x

array([300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420,
       430, 440, 450, 460, 470, 480, 490])

In [15]:
x.shape

(20,)

In [7]:
x.reshape(4,5)

array([[300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490]])

In [17]:
x= np.random.randint(-1000,1000, (20,20))
x

array([[ 317,   48,  217,  698,  842, -778,  -94,  373,  336,  867, -207,
         409, -719,   23,  637,  101,  538,  420, -266,  453],
       [-450,  915,  419, -166, -265, -637, -638, -682, -411, -610,  101,
        -723,  352,  797, -611, -906,  623,  -89, -910,  881],
       [-154,  722, -571, -955, -491,  789, -475, -309, -412,  497, -764,
         377,  672,  624, -535, -663,  -91, -973,   93, -598],
       [   7,  919,  766, -555,  684,  724, -124, -144, -585,   36, -424,
         780,  699,  688, -395,  265,  901,   37,  738,  552],
       [ -77, -345,  -43,  616,  544,    1, -839, -556, -408,  497, -698,
        -970,  752, -120,  168, -578,  441,  969,  440, -516],
       [-517, -220,  220, -193, -685,  501, -151,  724,   31, -352, -850,
         433,   72,  803, -262, -282,  946, -756, -491,  965],
       [ 324, -356, -164,  507,  783, -321, -959,  823, -519, -366,  781,
        -649, -784,  492,  833, -127, -974,  511, -583,  620],
       [ 906,   -3,  769,  141, -196,  70

In [18]:
x.max()

994

In [19]:
x.argmax()

377

In [20]:
x.shape

(20, 20)

In [21]:
x.min()

-997

In [29]:
x=np.array([3, 20, 30])
y=np.array([4 ,6, 7 ])
d = x - y
i = d**2
t = i[0]+i[1]+i[2]
print(i)
print(t)

[  1 196 529]
726
